version: "3"
services:
  app:
    restart: always
    build: .  # '点'代表当前目录
    command: bash -c "python3 manage.py collectstatic --no-input && gunicorn --timeout=30 --workers=4 --bind :8000 HelloWorld.wsgi:application"
    volumes:
      - .:/code
      - static-volume:/code/collected_static
    expose:
      - "8000"
    networks:
      - web_network

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - static-volume:/code/collected_static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

  networks:
    web_network:
      driver: bridge
    db_network:
      driver: bridge

  volumes:
    static-volume: