# Generated by Django 3.0.6 on 2020-07-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistor',
            name='count',
            field=models.IntegerField(default=1, verbose_name='访问次数'),
        ),
        migrations.AlterField(
            model_name='vistor',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300, verbose_name='user_agent'),
        ),
    ]
