# Generated by Django 3.0.6 on 2020-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20200731_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistor',
            name='count',
            field=models.IntegerField(default=0, verbose_name='访问次数'),
        ),
    ]
