# Generated by Django 3.0.6 on 2020-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200731_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistor',
            name='city',
            field=models.CharField(blank=True, max_length=300, verbose_name='user_agent'),
        ),
        migrations.AddField(
            model_name='vistor',
            name='country',
            field=models.CharField(blank=True, max_length=300, verbose_name='user_agent'),
        ),
        migrations.AddField(
            model_name='vistor',
            name='ip_as',
            field=models.CharField(blank=True, max_length=300, verbose_name='user_agent'),
        ),
        migrations.AddField(
            model_name='vistor',
            name='isp',
            field=models.CharField(blank=True, max_length=300, verbose_name='user_agent'),
        ),
    ]
