# Generated by Django 3.0.8 on 2020-08-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20200804_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
