# Generated by Django 3.0.5 on 2020-05-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20200502_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
