# Generated by Django 3.1 on 2020-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_message_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(),
        ),
    ]
