# Generated by Django 3.0.6 on 2020-09-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20200830_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='spider_article',
        ),
    ]
