# Generated by Django 3.0.6 on 2020-09-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20200904_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
