# Generated by Django 3.0.5 on 2020-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=30)),
                ('user_mail', models.CharField(max_length=30)),
            ],
        ),
    ]
