# Generated by Django 3.0.5 on 2020-05-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
